services:
  api:
    build:
      target: dev
    environment:
      NODE_ENV: development
    command: npm run dev:server
    volumes:
      - ./src:/app/src
      - ./tsconfig.json:/app/tsconfig.json:ro